before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-2.0
matrix:
    include:
       - language: julia
         julia: 0.6
         os: linux
         dist: trusty
         sudo: true
       - language: julia
         julia: nightly
         os: linux
         dist: trusty
         sudo: true
       - language: julia
         julia: 0.6
         os: linux
         sudo: true
       - language: julia
         julia: nightly
         os: linux
         sudo: true
       - language: julia
         julia: 0.6
         os: osx
       - language: julia
         julia: nightly
         os: osx
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("SDL2")); Pkg.add("SDL2"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
